/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../../../../../common";
import type {
  CrossDomainEnabled,
  CrossDomainEnabledInterface,
} from "../../../../../../../../sub/packages/tokamak/contracts/contracts/libraries/bridge/CrossDomainEnabled";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_messenger",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "messenger",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052341561000f57600080fd5b610166388190036080601f8201601f19168101906001600160401b038211908210171561004c57634e487b7160e01b600052604160045260246000fd5b6040528082608039602081121561006257600080fd5b50506080516001600160a01b038116811461007c57600080fd5b600080546001600160a01b0319166001600160a01b0383161790555060405160be806100a883398082f3fe6080604052600436106075576000803560e01c633cb747bf141560735734156025578081fd5b807ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc360112156052578081fd5b73ffffffffffffffffffffffffffffffffffffffff81541660805260206080f35b505b600080fdfea36469706673582212208cea00742a3825e87f72343f6a513abca59759f5f781967b7861b12ebd198b896c6578706572696d656e74616cf564736f6c63430008090041";

type CrossDomainEnabledConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: CrossDomainEnabledConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class CrossDomainEnabled__factory extends ContractFactory {
  constructor(...args: CrossDomainEnabledConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    _messenger: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<CrossDomainEnabled> {
    return super.deploy(
      _messenger,
      overrides || {}
    ) as Promise<CrossDomainEnabled>;
  }
  override getDeployTransaction(
    _messenger: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(_messenger, overrides || {});
  }
  override attach(address: string): CrossDomainEnabled {
    return super.attach(address) as CrossDomainEnabled;
  }
  override connect(signer: Signer): CrossDomainEnabled__factory {
    return super.connect(signer) as CrossDomainEnabled__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): CrossDomainEnabledInterface {
    return new utils.Interface(_abi) as CrossDomainEnabledInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CrossDomainEnabled {
    return new Contract(address, _abi, signerOrProvider) as CrossDomainEnabled;
  }
}
