/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IL1ERC20Bridge } from "./IL1ERC20Bridge";
export type { IL1StandardBridge } from "./IL1StandardBridge";
